version: '3'

services:
  credit-evaluation-service:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    command: npm run start:dev
